### ISSUE TITLE
export default XComponent does not work.

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-generator#20]
Shouldn't that be XComponent.register(); ?

**Comment by SheepFromHeaven** [comment]
@dweiger good idea, but we decided, the developer has to decide, when the component should be registered.
If you want to have the ready at startup, just import them in a main.ts and register them there.

I added biotope/biotope-element#42

**Comment by SheepFromHeaven** [comment]
@dweiger we have a good solution for that. Will be done soon 🚀
