### ISSUE TITLE
Adjust to bioElement v4

### ISSUE THREAD

**Issue by luke-m** [biotope/biotope-generator#66]
**Is your feature request related to a problem? Please describe.**
BioElements generated by biotope-generator do not apply the structure that the new version of BioElement needs. 

**Describe the solution you'd like**
Adjust the generated code to BioElement v4.

**Comment by luke-m** [comment]
I started working on it but ran into some issues with EJS syntax so I had to stop due to time constraints. Here's the branch: https://github.com/biotope/biotope-generator/tree/adjust-to-bioelement-v4

**Comment by SheepFromHeaven** [comment]
On it
